logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    listener:
      simple:
        prefetch: 1     # 每次只能获取一条消息，处理完成才能获取下一条信息
    host: 114.212.245.239    # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: chen # 用户名
    password: 010124cc # 密码